#!/usr/bin/env bash

#report to code coverage services
env COVERALLS_SERVICE_NAME="Jenkins" \
    COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN_DENDRO" \
    RUNNING_IN_JENKINS="1" \
    CODECLIMATE_REPO_TOKEN="$CODECLIMATE_REPO_TOKEN_DENDRO" \
    CODACY_PROJECT_TOKEN="$CODACY_PROJECT_TOKEN_DENDRO" \
    npm run report-coverage