SELECT ?descriptor AVG(?descriptor_length) as ?avg_descriptor_length 
{   
   SELECT ?descriptor ?descriptor_length 
   { 
       SELECT ?descriptor STRLEN(STR(?value)) as ?descriptor_length 
       FROM <http://dendro-prd.fe.up.pt:3005/dendro_graph> 
          WHERE 
          { 
              { 
                  { 
                      ?resource rdf:type nfo:FileDataObject. 
                  } 
                  UNION 
                  { 
                      ?resource rdf:type nfo:Folder. 
                  } 
              }. 
              { 
                  ?latest_version ddr:isVersionOf ?resource. 
                  { 
                      SELECT ?resource MAX(?version_number) as ?latest_version_number 
                      FROM <http://dendro-prd.fe.up.pt:3005/dendro_graph> 
                      WHERE 
                      { 
                          ?version ddr:isVersionOf ?resource. 
                          ?version ddr:versionNumber ?version_number. 
                      } 
              }. 
              ?latest_version ddr:versionNumber ?latest_version_number. 
              ?latest_version dcterms:created ?date_last_version_created. 
              ?latest_version ?descriptor ?value. 
              FILTER 
              ( 
                  STRSTARTS(STR(?descriptor), "http://purl.org/dc/terms/") 
                  && 
                  xsd:dateTime(?date_last_version_created) < xsd:dateTime("2015-04-20T16:29:50.882Z") 
              ) 
           }
       }
       ORDER BY DESC (?date_last_version_created)
   }
}