SELECT ?resource ?latest_version ?latest_version_number
{
	{
		SELECT ?resource ?latest_version ?latest_version_number 
		FROM <http://dendro-prd.fe.up.pt:3005/dendro_graph>
		WHERE 
		{
			{
				{
					?resource rdf:type nfo:FileDataObject.	
				}
				UNION
				{
					?resource rdf:type nfo:Folder.
				}
			}.
			{
				?latest_version ddr:isVersionOf ?resource.
				{
					SELECT ?resource MAX(?version_number) as ?latest_version_number
					FROM <http://dendro-prd.fe.up.pt:3005/dendro_graph>
					WHERE
					{
						?version ddr:isVersionOf ?resource.
						?version ddr:versionNumber ?version_number.
					}	
				}.

				?latest_version ddr:versionNumber ?latest_version_number.
				?latest_version dcterms:created ?date_last_version_created.

				FILTER
				(
					?date_last_version_created < "2015-05-24T09:56:32.347Z"
				)
			}
		}
	}
	UNION
	{
		SELECT ?resource ?latest_version ?latest_version_number 
		FROM <http://dendro-prd.fe.up.pt:3005/dendro_graph>
		WHERE 
		{
			{
				?resource rdf:type nfo:FileDataObject.	
				?resource dcterms:created ?date_resource_created
				FILTER NOT EXISTS
				{
					{
						?resource rdf:type ddr:ArchivedResource
					}
					UNION
					{
						?a_version ddr:isVersionOf ?resource.
						?a_version rdf:type ddr:ArchivedResource
					}
				}
				FILTER
				(
					?date_resource_created < "2015-05-24T09:56:32.347Z"
				)
			}
			UNION
			{
				?resource rdf:type nfo:Folder. 
				?resource dcterms:created ?date_resource_created
				FILTER NOT EXISTS
				{
					FILTER NOT EXISTS
					{
						{
						?resource rdf:type ddr:ArchivedResource
						}
						UNION
						{
							?a_version ddr:isVersionOf ?resource.
							?a_version rdf:type ddr:ArchivedResource
						}
					}
				}
				FILTER
				(
					?date_resource_created < "2015-05-24T09:56:32.347Z"
				)
			}
		}
	}
}
