SELECT ?interaction ?date_favorited ?descriptor
FROM <http://127.0.0.1:3001/dendro_graph>  
WHERE  
{  
	?interaction rdf:type ddr:Interaction. 
	?interaction ddr:executedOver ?descriptor.

	
	?interaction ddr:originallyRecommendedFor ?information_element.
	?information_element nie:isLogicalPartOf+ <http://127.0.0.1:3001/project/datanotes2>.
	
	?interaction dcterms:created ?date_favorited. 
	?interaction ddr:interactionType "favorite_descriptor_from_quick_list" . 
	
	?interaction ?p ?o.
} 