#!/usr/bin/env bash

ELASTICSEARCH_CONTAINER_NAME="elasticsearch-dendro"
VIRTUOSO_CONTAINER_NAME="virtuoso-dendro"
MYSQL_CONTAINER_NAME="mysql-dendro"
MONGODB_CONTAINER_NAME="mongodb-dendro"

ELASTICSEARCH_HOSTNAME="127.0.0.1"
VIRTUOSO_HOSTNAME="127.0.0.1"
MYSQL_HOSTNAME="127.0.0.1"
MONGODB_HOSTNAME="127.0.0.1"
